version: '3.3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0-amd64
    container_name: elasticsearch
    env_file:
      - elastic.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - observability

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.0-amd64
    container_name: kibana
    depends_on:
      - elasticsearch
    env_file:
      - kibana.env
    ports:
      - 5601:5601
    networks:
      - observability
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.1.0-amd64
    container_name: metricbeat
    user: root
    environment:
      - logging.level=warn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./beats/metric/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    restart: on-failure
    networks:
      - observability

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:8.1.0-amd64
    container_name: heartbeat
    user: root
    environment:
      - setup.kibana.host=kibana:5601
    volumes:
      - ./beats/heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    restart: on-failure
    networks:
      - observability

volumes:
  elasticsearch_data:

networks:
  observability:
    driver: bridge
